services:
  ros-desktop:
    image: ghcr.io/sloretz/ros:noetic-desktop
    network_mode: host
    environment:
      - ROS_HOSTNAME=localhost
      - ROS_MASTER_URI=http://localhost:11311
  ros-desktop-full:
    extends:
      file: common.yaml
      service: ros-desktop
    image: ghcr.io/sloretz/ros:noetic-desktop-full
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
